project/apps/user/urls.py
from django.urls import path

from .views import crear_user, crear_users_predeterminados, index, prueba_búsqueda

# Es necesario este nombre, para ser llamado desde la plantila,
# por ejemplo: {% url 'user:index' %}
app_name = "user"

urlpatterns = [
    path("", index, name="index"),
    path("crear-users-predeterminados/", crear_users_predeterminados, name="crear-users"),
    path("prueba-búsqueda/", prueba_búsqueda, name="prueba-búsqueda"),
    path("crear/", crear_user, name="crear"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path

from .views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("user/", include("user.urls")),
    path("rutina/", include("rutina.urls")),
]

project/apps/home/models.py
from django.db import models

# Create your models here.

project/apps/rutina/models.py
from django.db import models

# Create your models here.

project/apps/user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

project/apps/user/forms.py
from django import forms

from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["nombre", "apellido", "nacimiento"]

project/apps/home/views.py
from django.shortcuts import render

# Create your views here.

project/apps/rutina/views.py
from django.shortcuts import render

# Create your views here.

project/apps/user/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import User


def index(request):
    users_registros = User.objects.all()
    contexto = {"users": users_registros}
    return render(request, "user/index.html", contexto)


def crear_users_predeterminados(request):
    from datetime import date

    # Crear instancias de users
    User.objects.create(nombre="Almendra", apellido="Ruiseñor", nacimiento=date(2015, 1, 1))
    User.objects.create(nombre="Giordana", apellido="Tapello", nacimiento=date(2005, 2, 2))
    User.objects.create(nombre="Macarena", apellido="Litter", nacimiento=date(1990, 3, 3))
    User.objects.create(nombre="Jhiordana", apellido="Perez", nacimiento=date(2005, 2, 2))

    # url = reverse("user:index")
    return redirect("user:index")


def prueba_búsqueda(request):
    from datetime import date

    # Búsqueda por nombre que contenga "dana"
    users_nombre = User.objects.filter(nombre__contains="dana")

    # Búsqueda por fecha de nacimiento mayor a 2000
    users_nacimiento = User.objects.filter(nacimiento__gt=date(2000, 1, 1))

    # Búsqueda por país de origen vacío
    users_pais = User.objects.filter(pais_origen_id=None)

    contexto = {
        "users_nombre": users_nombre,
        "users_nacimiento": users_nacimiento,
        "users_pais": users_pais,
    }
    return render(request, "user/resultados_busqueda.html", contexto)


def crear_user(request):
    from .forms import UserForm

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("user:index"))
    else:  # method == "GET"
        form = UserForm()
    return render(request, "user/crear.html", {"form": form})

project/config/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

project/apps/user/templates/user/crear.html
{% extends 'base.html' %}

{% block TITULO %}Crear usuario{% endblock %}

{% block CONTENIDO %}

    <form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit">Guardar</button>
    </form>

{% endblock %}

project/apps/user/templates/user/index.html
{% extends 'base.html' %}

{% block TITULO %}USUARIOS{% endblock %}

{% block CONTENIDO %}
    {% for user in users %}
        <h2>{{ user.nombre }}</h2>
        <p>{{ user.apellido }}</p>
        <p>{{ user.nacimiento }}</p>
    {% endfor %}
    
    <a href="{% url 'user:crear-usuarios' %}">Crear datos de usuarios preestablecidos</a>
    <br>
    <a href="{% url 'user:prueba-búsqueda' %}">Prueba de búsqueda</a>
    <br>
    <a href="{% url 'user:crear' %}">Crear usuario</a>
    <br>
    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1 style="color:blue">
            {% block TITULO %}Gimnasio Django{% endblock %}
        </h1>

        {% block CONTENIDO %}{% endblock %}
        
    </body>
</html>

project/templates/index.html
{% extends 'base.html' %}

{% block CONTENIDO %}
    <div style="text-align: center; font-size: xx-large;">
        <a href="{% url 'user:index' %}">Ir a Usuarios</a>
        <br>
        <a href="{% url 'rutina:index' %}">Ir a Rutinas</a>
    </div>
{% endblock %}